# Naam van de workflow die wordt getoond in het "Actions"-tabblad
name: Development Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Stap 1: Haal de code uit uw repository op
      - name: Checkout repository
        uses: actions/checkout@v4

      # Stap 2: Installeer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Stap 3: Installeer de Python-afhankelijkheden via requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # --- VERBETERING: Installeer direct vanuit requirements.txt ---
          pip install -r requirements.txt

      # Stap 4: Bouw de .exe met PyInstaller
      - name: Build the executable
        run: |
          pyinstaller --onefile --windowed `
            --add-data "app/templates;app/templates" `
            --add-data "app/static;app/static" `
            --hidden-import waitress `
            --hidden-import markdown `
            --exclude "flask_session" `
            --name PyDesk `
            run.py

      # Stap 5: Upload de gebouwde .exe als een artefact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyDesk-dev
          path: dist/PyDesk.exe
